### ISSUE TITLE
equinox.custom_types > replace with jaxtyping

### ISSUE THREAD

**Issue by krahnikblis** [paganpasta/eqxvision#60]
hi there, since a recent change in eqx and split of functionality to google/jaxtyping, the import of PyTree and others from equinox.custom_types breaks and causes error. i can confirm i resolved locallish by running sed on all the files that import from that, changing to jaxtyping, and resolved the import errors, e.g. 
sed -i 's/equinox.custom_types/jaxtyping/' .local/lib/python3.7/site-packages/eqxvision/models/segmentation/_utils.py

**Comment by paganpasta** [comment]
Hi,

Thanks for pointing this out! Feel free to submit a PR for this issue. Else, I'll probably try and fix it in the next few days.

**Comment by paganpasta** [comment]
@krahnikblis Should be fixed in https://github.com/paganpasta/eqxvision/pull/61.
